#!/bin/bash
if [[ "$1" = "" ]]
then
  echo "Usage: $0 PREFIX"
  exit 1
fi
if zenity --question --icon-name warning --name "winedi" --title "Uninstall Program" --text "You are about to uninstall a program.\n\nThis cannot be undone. Proceed?"
then
  rm $1
else
  exit 1
fi
